name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.17.5
      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')

